# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# kakao login
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 사용자 인증
pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리

# google login
pod 'GoogleSignIn'

target 'Doit (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Doit (iOS)

end

target 'Doit (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Doit (macOS)

end
